#!/usr/bin/env python
# coding: utf-8

# In[3]:


import numpy as np


# # Тема “Вычисления с помощью Numpy”

# # Задание 1

# In[4]:


a = [[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]]


# In[5]:


a = np.array(a)
a


# In[6]:


mean_a = a.mean(axis=0)
mean_a


# # Задание 2

# In[7]:


a_centered = np.subtract(a, mean_a)
a_centered


# # Задание 3

# In[8]:


a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp


# In[9]:


a_centered_sp_n = a_centered_sp / (len(a_centered[:, 0])-1)
a_centered_sp_n


# # Задание 4

# In[10]:


a_trans = a.T
a_trans


# In[11]:


a_cov = np.cov(a_trans)
a_cov


# In[12]:


print(f'Коварация составляет: {a_cov[0, 1]}')


# In[ ]:




